#!/bin/sh
#
# Copyright (C) 2026 Neil Rackett
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Generate the embedded splash screen (splash.c) from a Degas PI1
# picture. Called from Makefile.atari; works with any POSIX od.
#
# usage: mksplash.sh SPLASH.PI1 splash.c

IN="$1"
OUT="$2"

SIZE=$(wc -c < "$IN" | tr -d ' ')
if [ "$SIZE" != "32034" ]; then
    echo "mksplash: $IN is $SIZE bytes, expected 32034 (Degas PI1)" >&2
    exit 1
fi

{
    echo "/*"
    echo " * Copyright (C) 2026 Neil Rackett"
    echo " * SPDX-License-Identifier: GPL-3.0-or-later"
    echo " */"
    echo "/*"
    echo " * Startup splash screen, generated by atari/mksplash.sh"
    echo " * from $IN - do not edit."
    echo " */"
    echo ""
    echo "const unsigned char nsdl_splash_pi1[32034] = {"
    # trim leading AND trailing blanks and drop empty lines: BSD od
    # (macOS) pads the final short line and appends a blank trailer,
    # which would otherwise end up as stray commas in the array
    od -An -v -tu1 "$IN" | sed -e 's/^ *//' -e 's/ *$//' \
        -e '/^$/d' -e 's/  */,/g' -e 's/$/,/'
    echo "};"
} > "$OUT"

# one comma per byte value in the array body - anything else means
# the od/sed pair misbehaved on this platform
COMMAS=$(sed -n '/{/,$p' "$OUT" | tr -dc ',' | wc -c | tr -d ' ')
if [ "$COMMAS" != "32034" ]; then
    echo "mksplash: generated $COMMAS values, expected 32034" >&2
    rm -f "$OUT"
    exit 1
fi
