[package]
name = "freenukum"
version = "0.3.5"
authors = ["Wolfgang Silbermayr <wolfgang@silbermayr.at>"]
edition = "2018"
default-run = "freenukum"
categories = ["games"]
license = "AGPL-3.0-or-later"
description = "A clone of the 1991 DOS game Duke Nukem 1"
readme = "README.md"
homepage = "https://gitlab.com/silwol/freenukum"
repository = "https://gitlab.com/silwol/freenukum"

[dependencies]
anyhow = "1"
directories-next = "2"
sdl2 = { version = "0.34", features = ["ttf", "image"] }
serde = "1"
serde_derive = "1"
toml = "0.5"
rand = "0.8"
explode = "0.1"
structopt = "0.3"
zip = "0.5"
log = "0.4"
rgb = "0.8"
