# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: Wolfgang Silbermayr <wolfgang@silbermayr.at>

[package]
name = "freenukum"
version = "0.4.0"
authors = ["Wolfgang Silbermayr <wolfgang@silbermayr.at>"]
edition = "2018"
default-run = "freenukum"
categories = ["games"]
license = "AGPL-3.0-or-later"
description = "A clone of the 1991 DOS game Duke Nukem 1"
readme = "README.md"
homepage = "https://salsa.debian.org/silwol/freenukum"
repository = "https://salsa.debian.org/silwol/freenukum"

[dependencies]
anyhow = "1"
directories-next = "2"
sdl2 = { version = "0.35.2", features = ["ttf", "image"] }
serde = "1"
serde_derive = "1"
toml = "0.5"
rand = "0.8"
explode = "0.1"
clap = { version = "3.1", features = ["derive"] }
zip = "0.6"
log = "0.4"
rgb = "0.8"
lazy_static = "1.4.0"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
