use crate::tile::Tiles;

// pub enum Sprites {
//     BackgroundAnimationTransparent0,
//     BackgroundAnimationTransparent1,
//     BackgroundAnimationTerminal,
//     BackgroundAnimationBlueFlash,
//     BackgroundAnimationRedLightPillar,
//     BackgroundAnimationBlueFlashPillar,
//     BackgroundAnimationMeasurementTerminal,
//     BackgroundAnimationRedAlertLight,
//     BackgroundAnimationUpArrow,
//     BackgroundAnimationBlueStripeFlashing,
//     BackgroundAnimationRedStripedWithChemicals,
//     BackgroundAnimationLava,
//     BackgroundGrayBrickWall0,
//     BackgroundGrayBrickWall1,
//     BackgroundGrayBrickWall2,
//     BackgroundGrayBrickWall3,
//     BackgroundGrayBrickWall4,
//     BackgroundGrayBrickWall5,
//     BackgroundGrayBrickWall6,
//     BackgroundGrayBrickWall7,
//     BackgroundSiloLeft,
//     BackgroundSiloCenter,
//     BackgroundSiloRight,
//     BackgroundSiloEdgleLeft,
//     BackgroundSiloEdgeCenter,
//     BackgroundSiloEdgeRight,
//     BackgroundGrayBrickWall8,
//     BackgroundGrayBrickWall9,
//     BackgroundMercuryMinesSignLeft,
//     BackgroundMercuryMinesSignRight,
//     BackgroundTimeMachineSignLeft,
//     BackgroundTimeMachineSignLeftRight,
// }

#[repr(usize)]
#[derive(Clone, Copy, Debug)]
enum BorderType {
    Left,
    VerticalMiddle,
    Top,
    Bottom,
    TopLeft,
    TopT,
    BottomT,
    BottomLeft,
    HorizontalMiddle,
    TopRight,
    Right,
    BottomRight,
    TopWithP,
    Middle,
    LeftT,
    RightT,
    TopWithR,
    MessageMiddle,
    MessageTopLeft,
    MessageTopRight,
    MessageBottomLeft,
    MessageBottomRight,
    MessageLeft,
    MessageRight,
    MessageTop,
    MessageBottom,
    BottomHelp0,
    BottomHelp1,
    BottomHelp2,
    BottomHelp3,
    Inventory0,
    Inventory1,
    Inventory2,
    FirePower0,
    FirePower1,
    FirePower2,
    Health0,
    Health1,
    Score0,
    Score1,
    TopWithF,
    TopWithS,
    HealthBlinking0,
    HealthBlinking1,
}

pub struct Sprites {}

impl Sprites {}
